WebProductos/Areas/Admin/Controllers/TipoProductoController.cs
using WebProductos.AccesoDatos.Repositorio.IRepositorio;
using WebProductos.Modelos;
using WebProductos.Utilidades;
using Microsoft.AspNetCore.Mvc;

namespace Bosque.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TipoProductoController : Controller
    {

        private readonly IUnidadTrabajo _unidadTrabajo;

        public TipoProductoController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            TipoProducto tipoproducto = new TipoProducto();

            if (id == null)
            {
                // Crear un nuevo item              
                return View(tipoproducto);
            }
            // Actualizamos
            tipoproducto = await _unidadTrabajo.TipoProducto.Obtener(id.GetValueOrDefault());
            if (tipoproducto == null)
            {
                return NotFound();
            }
            return View(tipoproducto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(TipoProducto tipoproducto)
        {
            if (ModelState.IsValid)
            {
                if (tipoproducto.Id == 0)
                {
                    await _unidadTrabajo.TipoProducto.Agregar(tipoproducto);
                    TempData[DS.Exitosa] = "Tipo producto creado Exitosamente";
                    
                }
                else
                {
                    _unidadTrabajo.TipoProducto.Actualizar(tipoproducto);
                    TempData[DS.Exitosa] = "Tipo producto actualizado Exitosamente";
                }
                await _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al grabar Tipo producto";
            return View(tipoproducto);
        }

        #region API

        [HttpGet]
        public async Task<IActionResult> ObtenerTodos()
        {
            var todos = await _unidadTrabajo.TipoProducto.ObtenerTodos();
            return Json(new { data = todos });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var tipoproductoDb = await _unidadTrabajo.TipoProducto.Obtener(id);
            if (tipoproductoDb == null)
            {
                return Json(new { success = false, message = "Error al borrar Tipo Producto" });
            }
            _unidadTrabajo.TipoProducto.Remover(tipoproductoDb);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Tipo Producto borrado exitosamente" });
        }        

        #endregion

    }
}

WebProductos/Areas/Inventario/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebProductos.Modelos.ViewModels;

namespace WebProductos.Areas.Inventario.Controllers
{
    [Area("Inventario")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebProductos/Areas/Admin/Views/TipoProducto/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-6">
        <h2 class="text-primary">Todos los Tipos de Productos</h2>
    </div>
    <div class="col-lg-6">
        <a class="btn btn-outline-primary" asp-action="Upsert"> <i class="bi bi-plus-square-fill"></i> Agregar más Tipos </a>
    </div>
</div>

<br />

<div class="p-4 border rounded bg-light">
    <table id="tblDatos" class="table table-responsive table-hover display nowrap" cellspacing="0" width="100%">
        <thead class="table-dark">
            <tr>
                <th>Tipo de Producto</th>
                <th>Descripcion</th>
                <th>Detalles</th>
                <th></th>
            </tr>
        </thead>
    </table>

</div>

@section Scripts {
    <script src="~/js/tipoproducto.js"></script>
}

WebProductos/Areas/Admin/Views/TipoProducto/Upsert.cshtml
@model WebProductos.Modelos.TipoProducto

@{

    Layout = "~/Views/Shared/_Layout.cshtml";
    var titulo = "Crear Tipo producto";
}

<form method="post">
    <div style="padding-left:15%; padding-right:15%; padding-bottom:inherit.4rem;">
        <div class="row border-0">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        </div>

        @if(Model.Id !=0)
        {
            // Actualizar
            titulo = "Actualizar";
            <input type="hidden" asp-for="Id" id="id" />
        }
        <div class="col-12 border-bottom p-0">
            <h2 class="text-primary">@titulo</h2>
        </div>

        <div class="row mb-2 mt-2">
            <div class="form-group col-md-6">
                <label>Tipo de Producto</label>
                <input type="text" asp-for="Tipo" class="form-control" placeholder="Tipo de Producto" id="tipoproducto" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
        </div>         
        <div class="row mb-2 mt-2">
            <div class="form-group col-md-6">
                <label>Descripción</label>
                <input type="text" asp-for="Descripcion" class="form-control" placeholder="Descripcion" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
        </div>
        <div class="row mb-2 mt-2">
            <div class="form-group col-md-6">
                <label>Detalles</label>
                <input type="text" asp-for="Detalles" class="form-control" placeholder="Agrega Detalles" />
                <span asp-validation-for="Detalles" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div>
            @if(Model.Id !=0)
            {
                <partial name="_BotonesActualizarRegresar" model="Model.Id" />
            }
            else
            {
                <partial name="_BotonesCrearRegresar" />
            }
        </div>

    </div>


</form>

WebProductos/Areas/Inventario/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">¡Bienvenidos al sitio web de MIGUEL HERNANDEZ CUEVAS</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebProductos/Views/Shared/_BotonesActualizarRegresar.cshtml
@model int

<div class="d-grid gap-2 d-md-block">
    <button type="submit" class="btn btn-primary" onfocus="false" asp-route-id="@Model">  <i class="bi bi-pencil-square"></i> Guardar Cambios </button>
    <a asp-action="Index" class="btn btn-success"> <i class="bi bi-arrow-return-left"></i> Regresar </a>
</div>

WebProductos/Views/Shared/_BotonesCrearRegresar.cshtml
<div class="d-grid gap-2 d-md-block">
    <button type="submit" class="btn btn-primary" onfocus="false">  <i class="bi bi-plus-square-fill"></i> Crear </button>
    <a asp-action="Index" class="btn btn-success"> <i class="bi bi-arrow-return-left"></i> Regresar </a>
</div>

WebProductos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebProductos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProductos.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bosque.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,400&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebProductos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                Entidades
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="TipoProducto" asp-action="Index">Tipo de Productos</a></li>
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Producto" asp-action="Index">Productos</a></li>               
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notificaciones" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebProductos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebProductos/Views/Shared/_Notificaciones.cshtml
@using WebProductos.Utilidades

@if (TempData[DS.Exitosa] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[DS.Exitosa]');
    </script>
}


@if (TempData[DS.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[DS.Error]');
    </script>
}